services:
  db:
    image: postgres:18-alpine
    volumes:
      - db-data:/var/lib/postgresql
    ports:
      - "5434:5432"
    healthcheck:
      test: [ "CMD", "psql", "-U", "root", "-d", "cinema_db", "-c", "SELECT 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_DB=cinema_db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password

  trailers-api:
    build: https://github.com/Theryston/trailers-api.git
    ports:
      - "3456:3000"
    environment:
      DATA_FOLDER: /data
    volumes:
      - ./data/trailers-api:/data

volumes:
  db-data:

