// Generated by cinema-schema-codegen. Do not edit.

#![allow(clippy::needless_lifetimes, dead_code, non_camel_case_types, unused_imports)]

use axum::extract::State;
use axum::routing::post;
use axum::{Json, Router};
use crate::app::{AppContext, EventBus};
use crate::rpc::{RpcResponse, ok};

pub fn rpc_router() -> Router<AppContext> {
    Router::new()
}

#[derive(Clone)]
pub struct Events {
}

impl Events {
    pub fn new(_bus: EventBus) -> Self {
        Self {
        }
    }
}
