// Generated by draad-codegen. Do not edit.

export type CollectionRequest = { collection: string, media_type: string, tmdb_id: number, title: string, poster_path: string | null, };

export type CollectionItem = { collection: string, media_type: string, tmdb_id: number, title: string, poster_path: string | null, added_at: string, position: number, };

export type CollectionStatus = { in_collection: boolean, };

export type CollectionDef = { slug: string, title: string, kind: string, created_at: string, system: number, hidden: number, };

export type CreateCollection = { slug: string, title: string, kind: string, };

export type ReorderItem = { media_type: string, tmdb_id: number, };

/**
 * Streaming progress for an active download. Emitted periodically by the
 * download worker; subscribers should treat updates as best-effort.
 */
export type DownloadProgress = { id: number, downloaded_bytes: number, total_bytes: number | null, status: string, };

export type EnqueueDownload = { media_type: string, tmdb_id: number, title: string, poster_path: string | null, season: number, episode: number, resolution: string, info_hash: string | null, file_idx: number | null, };

export type ResolutionEstimate = { resolution: string, size_bytes: number | null, size_display: string | null, streams_count: number, };

export type Download = { id: number, media_type: string, tmdb_id: number, title: string, poster_path: string | null, season: number, episode: number, resolution: string | null, info_hash: string, file_idx: number, file_path: string, total_bytes: number | null, downloaded_bytes: number, status: string, error: string | null, created_at: string, completed_at: string | null, };

/**
 * One connected WebSocket client, as seen by every other client. The full
 * roster is broadcast on the `remote_presence` topic whenever it changes, so a
 * phone can discover TVs to pair with and a TV can detect a remote pairing to
 * it. There is no auth/user concept on the server — pairing is presence-based
 * and assumes a trusted local network.
 */
export type ClientPresence = { 
/**
 * Per-window client id, browser-generated and held in `sessionStorage`
 * (unique per tab, stable across reloads).
 */
id: string, 
/**
 * Human label shown in the pairing UI (e.g. "Chrome · macOS").
 */
label: string, 
/**
 * Coarse device class from viewport width: `phone` | `tablet` | `desktop`.
 */
kind: string, 
/**
 * Viewport width in CSS pixels. Used for relative sizing — with a
 * single-user assumption, the smaller of two clients is the candidate
 * remote and the larger is the TV.
 */
width: number, 
/**
 * Current role: `browser` | `tv` | `remote`.
 */
mode: string, 
/**
 * When this client is a `remote`, the id of the TV it controls.
 */
paired_to: string | null, };

export type YoutubeCookiesStatus = { 
/**
 * `"none"`, `"file"`, or `"env"` — which cookies source yt-dlp is using.
 */
source: string, 
/**
 * Size of the stored cookies file (only set when `source == "file"`).
 */
size: number | null, 
/**
 * Path the env override points at (only set when `source == "env"`).
 */
env_path: string | null, };

export type StartStream = { url: string, local: boolean, };

export type RemuxSession = { session_id: string, playlist_url: string, };

export type StreamStats = { progress_bytes: number, total_bytes: number, download_speed_mbps: number, peers: number, finished: boolean, };

/**
 * Periodic per-torrent stats broadcast over WebSocket. Carries the
 * `info_hash` so subscribers can filter to the stream they care about
 * (a single topic fans out updates for every active torrent)
 */
export type StreamStatsUpdate = { info_hash: string, progress_bytes: number, total_bytes: number, download_speed_mbps: number, peers: number, finished: boolean, };

export type AudioTracks = { tracks: AudioTrack[], subtitles: EmbeddedSubtitleTrack[], duration: number | null, chapters: Chapter[], };

/**
 * Per-file piece-availability bitmap broadcast over WebSocket. 200 buckets,
 * 0..=255 each. Emitted only for files currently being streamed.
 */
export type PiecesUpdate = { info_hash: string, file_idx: number, pieces: number[], };

export type Stream = { info_hash: string, file_idx: number, name: string, title: string, source: string, resolution: string | null, codec: string | null, audio: string | null, source_type: string | null, hdr: boolean, imax: boolean, seeders: number | null, size_bytes: number | null, size_display: string | null, score: number, };

export type SubtitleTrack = { id: string, language: string, url: string, 
/**
 * Higher score = more likely to be in sync
 */
score: number, };

export type SubtitleCue = { 
/**
 * Start time in seconds
 */
start: number, 
/**
 * End time in seconds
 */
end: number, text: string, };

export type MediaItem = { id: number, imdb_id: string | null, media_type: MediaType, title: string, overview: string | null, tagline: string | null, release_date: string | null, runtime: number | null, rating: number | null, poster_path: string | null, backdrops: string[], genres: Genre[], videos: Video[], logo_path: string | null, seasons: Season[] | null, cast: CastMember[], directors: CrewMember[], next_episode: NextEpisode | null, };

export type NextEpisode = { season_number: number, episode_number: number, name: string, air_date: string | null, still_path: string | null, };

export type CastMember = { id: number, name: string, character: string | null, profile_path: string | null, };

export type CrewMember = { id: number, name: string, job: string, profile_path: string | null, };

export type MediaType = "movie" | "tv";

export type SearchResult = { id: number, media_type: MediaType, title: string, overview: string | null, release_date: string | null, poster_path: string | null, backdrop_path: string | null, };

export type Genre = { id: number, name: string, };

export type Video = { key: string, site: string, name: string, video_type: string, 
/**
 * Whether TMDB marks this as an official (studio-published) video.
 */
official: boolean, 
/**
 * Max resolution reported by TMDB (e.g. 360, 720, 1080, 2160).
 */
size: number, 
/**
 * ISO-8601 publish timestamp, used to prefer the most recent trailer.
 */
published_at: string | null, };

export type Season = { id: number, season_number: number, name: string, episode_count: number, poster_path: string | null, air_date: string | null, episodes: Episode[], };

export type Episode = { episode_number: number, name: string, overview: string | null, stills: string[], };

export type AudioTrack = { 
/**
 * ffmpeg absolute stream index
 */
index: number, 
/**
 * audio-only index (0, 1, 2...)
 */
stream_index: number, name: string, language: string | null, codec: string, };

export type EmbeddedSubtitleTrack = { 
/**
 * ffmpeg absolute stream index
 */
index: number, 
/**
 * subtitle-only index (0, 1, 2...)
 */
stream_index: number, language: string | null, name: string, codec: string, };

export type Chapter = { 
/**
 * chapter start time in seconds
 */
start: number, 
/**
 * chapter end time in seconds
 */
end: number, title: string, };

/** Display metadata for a cached trailer. */
export type TrailerMeta = { aspect: number, };

export type RecordWatch = { media_type: string, tmdb_id: number, title: string, poster_path: string | null, season: number | null, episode: number | null, info_hash: string | null, file_idx: number | null, progress: number | null, duration: number | null, };

export type WatchHistoryItem = { media_type: string, tmdb_id: number, title: string, poster_path: string | null, season: number, episode: number, info_hash: string | null, file_idx: number, progress: number, duration: number, last_watched: string, };

export class CollectionsApi {
	constructor(private rpc: Rpc) {}

	/**
	 * Adds an item to a named collection
	 * @throws {RpcError<Error>}
	 */
	add(item: CollectionRequest): Promise<void> {
		return this.rpc.call("collections/add", { item });
	}

	/**
	 * Removes an item from a collection
	 * @throws {RpcError<Error>}
	 */
	remove(collection: string, media_type: string, id: number): Promise<void> {
		return this.rpc.call("collections/remove", { collection, media_type, id }, "DELETE");
	}

	/**
	 * Lists items in a single collection, ordered by position then added time
	 * @throws {RpcError<Error>}
	 */
	get(collection: string): Promise<CollectionItem[]> {
		return this.rpc.call("collections/get", { collection }, "GET");
	}

	/**
	 * Whether the given item is in the given collection
	 * @throws {RpcError<Error>}
	 */
	contains(collection: string, media_type: string, id: number): Promise<CollectionStatus> {
		return this.rpc.call("collections/contains", { collection, media_type, id }, "GET");
	}

	/**
	 * Lists every collection definition (user + system), ordered by position
	 * @throws {RpcError<Error>}
	 */
	listDefs(): Promise<CollectionDef[]> {
		return this.rpc.call("collections/list_defs", {}, "GET");
	}

	/**
	 * Creates (or upserts) a collection definition
	 * @throws {RpcError<Error>}
	 */
	createDef(def: CreateCollection): Promise<void> {
		return this.rpc.call("collections/create_def", { def }, "PUT");
	}

	/**
	 * Deletes a collection definition and all its items. System defs can't
	 * be deleted
	 * @throws {RpcError<Error>}
	 */
	deleteDef(slug: string): Promise<void> {
		return this.rpc.call("collections/delete_def", { slug }, "DELETE");
	}

	/**
	 * Hides/unhides a collection from the UI without deleting its items
	 * @throws {RpcError<Error>}
	 */
	setVisibility(slug: string, hidden: boolean): Promise<void> {
		return this.rpc.call("collections/set_visibility", { slug, hidden }, "PATCH");
	}

	/**
	 * Reorders the list of collection definitions
	 * @throws {RpcError<Error>}
	 */
	reorderDefs(slugs: string[]): Promise<void> {
		return this.rpc.call("collections/reorder_defs", { slugs }, "PATCH");
	}

	/**
	 * Reorders items within a single collection
	 * @throws {RpcError<Error>}
	 */
	reorder(collection: string, items: ReorderItem[]): Promise<void> {
		return this.rpc.call("collections/reorder", { collection, items }, "PATCH");
	}
}

export class DownloadsApi {
	constructor(private rpc: Rpc) {}

	/**
	 * Lists every download ever queued, newest first
	 * @throws {RpcError<Error>}
	 */
	list(): Promise<Download[]> {
		return this.rpc.call("downloads/list", {}, "GET");
	}

	/**
	 * Cancels an in-progress download and removes its row + files from disk
	 * @throws {RpcError<Error>}
	 */
	delete(id: number): Promise<void> {
		return this.rpc.call("downloads/delete", { id }, "DELETE");
	}

	/**
	 * Queues a download. If `info_hash`/`file_idx` are omitted, picks the
	 * best stream matching the requested resolution
	 * @throws {RpcError<Error>}
	 */
	enqueue(request: EnqueueDownload): Promise<void> {
		return this.rpc.call("downloads/enqueue", { request });
	}

	/**
	 * Bandwidth/size estimates per available resolution
	 * @throws {RpcError<Error>}
	 */
	estimate(media_type: string, tmdb_id: number): Promise<ResolutionEstimate[]> {
		return this.rpc.call("downloads/estimate", { media_type, tmdb_id }, "GET");
	}
}

export class HlsApi {
	constructor(private rpc: Rpc) {}

	/**
	 * Stops an HLS transcoding session and tears down its ffmpeg process
	 * @throws {RpcError<Error>}
	 */
	stop(session_id: string): Promise<void> {
		return this.rpc.call("hls/stop", { session_id }, "DELETE");
	}
}

export class MediaApi {
	constructor(private rpc: Rpc) {}

	/**
	 * Full TMDB details for a movie
	 * @throws {RpcError<Error>}
	 */
	movieDetails(id: number): Promise<MediaItem> {
		return this.rpc.call("media/movie_details", { id }, "GET");
	}

	/**
	 * Full TMDB details for a TV show
	 * @throws {RpcError<Error>}
	 */
	tvDetails(id: number): Promise<MediaItem> {
		return this.rpc.call("media/tv_details", { id }, "GET");
	}

	/**
	 * Items similar to the given movie/TV id
	 * @throws {RpcError<Error>}
	 */
	similar(media_type: string, id: number): Promise<SearchResult[]> {
		return this.rpc.call("media/similar", { media_type, id }, "GET");
	}

	/**
	 * Currently-trending movies + TV
	 * @throws {RpcError<Error>}
	 */
	trending(): Promise<SearchResult[]> {
		return this.rpc.call("media/trending", {}, "GET");
	}
}

export class RemoteApi {
	constructor(private rpc: Rpc) {}

	/**
	 * Returns the caller's own presence and pushes it back down their socket
	 * (`remote_self`). Demonstrates injecting the live connection into an HTTP
	 * handler — the `conn` arg is server-filled, so the generated TS is just
	 * `whoami(): Promise<ClientPresence>`. 409s if the caller has no live socket.
	 * @throws {RpcError<Error>}
	 */
	whoami(): Promise<ClientPresence> {
		return this.rpc.call("remote/whoami");
	}
}

export class SearchApi {
	constructor(private rpc: Rpc) {}

	/**
	 * Full-text search across TMDB titles
	 * @throws {RpcError<Error>}
	 */
	search(q: string): Promise<SearchResult[]> {
		return this.rpc.call("search/search", { q }, "GET");
	}
}

export class SettingsApi {
	constructor(private rpc: Rpc) {}

	/**
	 * Returns the active yt-dlp cookies source.
	 * @throws {RpcError<Error>}
	 */
	youtubeCookiesStatus(): Promise<YoutubeCookiesStatus> {
		return this.rpc.call("settings/youtube_cookies_status", {}, "GET");
	}

	/**
	 * Stores a Netscape-format `cookies.txt` body in the data dir so yt-dlp
	 * can use it on subsequent trailer requests.
	 * @throws {RpcError<Error>}
	 */
	setYoutubeCookies(content: string): Promise<YoutubeCookiesStatus> {
		return this.rpc.call("settings/set_youtube_cookies", { content }, "PUT");
	}

	/**
	 * Removes the stored cookies file (the env override, if any, still wins).
	 * @throws {RpcError<Error>}
	 */
	clearYoutubeCookies(): Promise<YoutubeCookiesStatus> {
		return this.rpc.call("settings/clear_youtube_cookies", {}, "DELETE");
	}
}

export class StreamsApi {
	constructor(private rpc: Rpc) {}

	/**
	 * Aggregates available torrent streams for a movie.
	 * @throws {RpcError<Error>}
	 */
	movie(id: number): Promise<Stream[]> {
		return this.rpc.call("streams/movie", { id }, "GET");
	}

	/**
	 * Aggregates available torrent streams for a specific TV episode.
	 * @throws {RpcError<Error>}
	 */
	tv(id: number, season: number, episode: number): Promise<Stream[]> {
		return this.rpc.call("streams/tv", { id, season, episode }, "GET");
	}

	/**
	 * Starts a torrent (idempotent) and returns the playback URL.
	 * @throws {RpcError<Error>}
	 */
	start(info_hash: string, file_idx: number): Promise<StartStream> {
		return this.rpc.call("streams/start", { info_hash, file_idx });
	}

	/**
	 * Reveals the on-disk file for a torrent stream in the server's file
	 * manager. Only meaningful when the server runs on the user's own machine
	 * (the self-hosted local case).
	 * @throws {RpcError<Error>}
	 */
	reveal(info_hash: string, file_idx: number): Promise<void> {
		return this.rpc.call("streams/reveal", { info_hash, file_idx });
	}

	/**
	 * Starts an HLS remux/transcode session for a file and returns its
	 * playlist URL (feed to hls.js). Callers stop the previous session first.
	 * @throws {RpcError<Error>}
	 */
	remux(info_hash: string, file_idx: number, audio: number, t: number, only_audio: boolean): Promise<RemuxSession> {
		return this.rpc.call("streams/remux", { info_hash, file_idx, audio, t, only_audio });
	}

	/**
	 * Current torrent download stats for a stream.
	 * @throws {RpcError<Error>}
	 */
	stats(info_hash: string): Promise<StreamStats> {
		return this.rpc.call("streams/stats", { info_hash }, "GET");
	}

	/**
	 * Per-piece availability bitmap (200 buckets) for a given file in a torrent.
	 * @throws {RpcError<Error>}
	 */
	pieces(info_hash: string, file_idx: number): Promise<number[]> {
		return this.rpc.call("streams/pieces", { info_hash, file_idx }, "GET");
	}

	/**
	 * Embedded audio + subtitle tracks + duration for a downloaded file.
	 * @throws {RpcError<Error>}
	 */
	audioTracks(info_hash: string, file_idx: number): Promise<AudioTracks> {
		return this.rpc.call("streams/audio_tracks", { info_hash, file_idx }, "GET");
	}

	/**
	 * Extracts cues from an embedded subtitle track in the source file.
	 * @throws {RpcError<Error>}
	 */
	embeddedSubtitles(info_hash: string, file_idx: number, stream_index: number): Promise<SubtitleCue[]> {
		return this.rpc.call("streams/embedded_subtitles", { info_hash, file_idx, stream_index }, "GET");
	}
}

export class SubtitlesApi {
	constructor(private rpc: Rpc) {}

	/**
	 * External subtitle tracks (OpenSubtitles etc.) for a movie
	 * @throws {RpcError<Error>}
	 */
	movie(id: number): Promise<SubtitleTrack[]> {
		return this.rpc.call("subtitles/movie", { id }, "GET");
	}

	/**
	 * External subtitle tracks for a specific TV episode
	 * @throws {RpcError<Error>}
	 */
	tv(id: number, season: number, episode: number): Promise<SubtitleTrack[]> {
		return this.rpc.call("subtitles/tv", { id, season, episode }, "GET");
	}

	/**
	 * Fetches and parses cues from an SRT URL
	 * @throws {RpcError<Error>}
	 */
	cues(url: string): Promise<SubtitleCue[]> {
		return this.rpc.call("subtitles/cues", { url }, "GET");
	}
}

export class TrailerApi {
	constructor(private rpc: Rpc) {}

	/**
	 * Display metadata (aspect ratio) for a cached trailer, used to size the
	 * player before the video's intrinsic dimensions are known.
	 * @throws {RpcError<Error>}
	 */
	meta(key: string): Promise<TrailerMeta> {
		return this.rpc.call("trailer/meta", { key }, "GET");
	}
}

export class WatchApi {
	constructor(private rpc: Rpc) {}

	/**
	 * Inserts the current playback position for a piece of media
	 * @throws {RpcError<Error>}
	 */
	record(watch: RecordWatch): Promise<void> {
		return this.rpc.call("watch/record", { watch });
	}

	/**
	 * Returns the 20 most-recently-watched items
	 * @throws {RpcError<Error>}
	 */
	history(): Promise<WatchHistoryItem[]> {
		return this.rpc.call("watch/history", {}, "GET");
	}
}

export class DownloadsEvents {
	constructor(private rpc: Rpc) {}

	/** Per-download bandwidth/status tick. Topic: `downloads_progress`. */
	onProgress(handler: (payload: DownloadProgress) => void): UnlistenFn {
		return this.rpc.listen<DownloadProgress>("downloads/progress", handler);
	}
}

export class RemoteEvents {
	constructor(private rpc: Rpc) {}

	/**
	 * Full roster of connected clients, re-broadcast on every
	 * connect / disconnect / role change. Topic: `remote_presence`.
	 * Subscribers diff it client-side to drive pairing.
	 */
	onPresence(handler: (payload: ClientPresence[]) => void): UnlistenFn {
		return this.rpc.listen<ClientPresence[]>("remote/presence", handler);
	}
}

export class StreamsEvents {
	constructor(private rpc: Rpc) {}

	/**
	 * Per-torrent download stats, emitted every ~2s for each active torrent.
	 * Topic: `streams_stats`. Subscribers filter by `info_hash`.
	 */
	onStats(handler: (payload: StreamStatsUpdate) => void): UnlistenFn {
		return this.rpc.listen<StreamStatsUpdate>("streams/stats", handler);
	}

	/**
	 * Per-file piece bitmap, emitted every ~2s for each file currently
	 * being streamed. Topic: `streams_pieces`. Subscribers filter by
	 * `(info_hash, file_idx)`.
	 */
	onPieces(handler: (payload: PiecesUpdate) => void): UnlistenFn {
		return this.rpc.listen<PiecesUpdate>("streams/pieces", handler);
	}
}

export class Urls {

	/** Range-served video bytes for a torrent file. */
	stream(infoHash: string, fileIdx: number): string {
		return `/api/stream/${encodeURIComponent(infoHash)}/${fileIdx}`;
	}

	/** An HLS playlist or segment for a transcode session. */
	hls(sessionId: string, file: string): string {
		return `/api/hls/${encodeURIComponent(sessionId)}/${encodeURIComponent(file)}`;
	}

	/**
	 * Cached/proxied TMDB image. `{*path}` is `{size}{tmdb_path}` (holds a
	 * slash), so it's interpolated raw rather than URL-encoded.
	 */
	image(path: string): string {
		return `/api/image/${path}`;
	}

	/** Range-served file from storage. */
	file(path: string): string {
		return `/api/files/${path}`;
	}

	/** Trailer video bytes for a YouTube key. */
	trailer(key: string): string {
		return `/api/trailer/${encodeURIComponent(key)}`;
	}
}

export class Api {
	collections: CollectionsApi;
	downloads: DownloadsApi;
	hls: HlsApi;
	media: MediaApi;
	remote: RemoteApi;
	search: SearchApi;
	settings: SettingsApi;
	streams: StreamsApi;
	subtitles: SubtitlesApi;
	trailer: TrailerApi;
	watch: WatchApi;
	downloadsEvents: DownloadsEvents;
	remoteEvents: RemoteEvents;
	streamsEvents: StreamsEvents;
	urls: Urls;

	constructor(private rpc: Rpc) {
		this.collections = new CollectionsApi(rpc);
		this.downloads = new DownloadsApi(rpc);
		this.hls = new HlsApi(rpc);
		this.media = new MediaApi(rpc);
		this.remote = new RemoteApi(rpc);
		this.search = new SearchApi(rpc);
		this.settings = new SettingsApi(rpc);
		this.streams = new StreamsApi(rpc);
		this.subtitles = new SubtitlesApi(rpc);
		this.trailer = new TrailerApi(rpc);
		this.watch = new WatchApi(rpc);
		this.downloadsEvents = new DownloadsEvents(rpc);
		this.remoteEvents = new RemoteEvents(rpc);
		this.streamsEvents = new StreamsEvents(rpc);
		this.urls = new Urls();
	}

	/**
	 * Subscribe to every failed RPC call from this `Api`.
	 * The handler fires *before* the promise rejects, so local
	 * `try { ... } catch (e)` blocks still see the error too.
	 * Returns an unsubscribe handle, or a no-op if the underlying
	 * transport does not implement `onError`.
	 */
	onError(handler: (err: RpcError) => void): UnlistenFn {
		return this.rpc.onError?.(handler) ?? (() => {});
	}
}

/** Returned by `Rpc.listen`, call to unsubscribe. */
export type UnlistenFn = () => void;

/** HTTP verb a generated method maps to. */
export type HttpVerb = "GET" | "POST" | "PUT" | "PATCH" | "DELETE";

/**
 * Transport contract the generated API classes call into. Implement this
 * in your app (using fetch / axios / tauri / etc.) and pass it to
 * `new Api(rpc)`. Or use `defaultRpc(...)` below.
 */
export interface Rpc {
	/**
	 * Send an RPC request. The wire command is `{namespace}/{method}`.
	 * Verb defaults to POST (body-bearing); GET/DELETE callers must pass
	 * the verb explicitly so `args` is serialised as a query string.
	 */
	call<T>(command: string, args?: Record<string, unknown>, method?: HttpVerb): Promise<T>;

	/** Subscribe to a backend event. Returns an unsubscribe handle. */
	listen<T>(topic: string, handler: (payload: T) => void): UnlistenFn;

	/**
	 * Run `handler` every time the event socket (re)connects, *after* live
	 * subscriptions have been restored. Use it to re-establish per-session
	 * state on the server (e.g. re-announce presence). Optional on the
	 * interface — custom transports can omit it.
	 */
	onOpen?(handler: () => void): UnlistenFn;

	/**
	 * Send a raw application frame to the server over the event socket —
	 * e.g. a presence announce or a client→client publish. The shape is
	 * app-defined; draad reserves only `{type:"subscribe"|"unsubscribe"}`.
	 * Connects the socket on demand and buffers until it's open. Optional
	 * on the interface.
	 */
	send?(frame: Record<string, unknown>): void;

	/**
	 * Subscribe to every failed RPC call. The handler fires *before* the
	 * promise rejects, so local `try { ... } catch (e)` paths still see
	 * the error too. Useful for global concerns: toast on error, route
	 * 401s to a sign-in flow, ship a Sentry breadcrumb, etc. Optional on
	 * the interface — custom transports can omit it.
	 */
	onError?(handler: (err: RpcError) => void): UnlistenFn;
}

/**
 * Thrown (or returned) by `Rpc.call` implementations on failure.
 *
 * The generic `E` is the shape of the server's error body — generated
 * methods tag their `@throws` with the concrete error type pulled from
 * the trait's `Result<_, E>` return.
 */
export class RpcError<E = unknown> extends Error {
	constructor(
		public readonly code: string,
		/** HTTP status code from the response (or 0 if the request never reached the server). */
		public readonly status: number,
		/**
		 * Parsed JSON body from the server, when present. Falls back to
		 * the raw response text on non-JSON responses, and to `null`
		 * when the body was empty.
		 */
		public readonly body: E | string | null,
		message: string,
	) {
		super(message);
		this.name = "RpcError";
	}
}

/**
 * A connected client: the unified transport handle returned by
 * {@link defaultRpc}. `call` rides HTTP; `listen` / `send` / events ride the
 * WebSocket channel. Carries the server-assigned {@link Conn.id} that ties the
 * two together.
 */
export interface Conn extends Rpc {
	/**
	 * Server-assigned, reconnect-stable client id. `null` until the first
	 * `$draad/welcome` frame arrives after the initial connect; stable across
	 * reconnects thereafter. Sent as the `x-draad-client` header on every
	 * `call` and as `?resume=` on WebSocket reconnects.
	 */
	readonly id: string | null;
}

export type DefaultRpcOptions = {
	/** Base URL for RPC calls. Requests go to `${baseUrl}/${command}`. */
	baseUrl?: string;
	/** WebSocket URL for events. Omit to make `listen()` throw. */
	wsUrl?: string;
	/** Extra headers added to every RPC call. */
	headers?: Record<string, string>;
	/** Disable WebSocket auto-reconnect. Default: true. */
	reconnect?: boolean;
	/** Cap on the backoff between reconnect attempts. Default: 30000. */
	maxReconnectDelayMs?: number;
};

/**
 * Default `Rpc` implementation: POST JSON for calls, a shared WebSocket
 * for events. Wire format:
 *
 *  - Calls: `POST {baseUrl}/{command}` with body `args`. 2xx responses
 *    are parsed as JSON and returned; non-2xx are thrown as `RpcError`.
 *  - Events: WS frames shaped `{ topic: string, payload: T }`.
 *
 * Auto-reconnects with exponential backoff + jitter (capped at
 * `maxReconnectDelayMs`) as long as there are active subscribers. Replace
 * with your own `Rpc` for auth, custom transports, or a different wire
 * format.
 */
export function defaultRpc(opts: DefaultRpcOptions = {}): Conn {
	const baseUrl = opts.baseUrl ?? "/api";
	const maxDelayMs = opts.maxReconnectDelayMs ?? 30000;
	const shouldReconnect = opts.reconnect !== false;
	const subs = new Map<string, Set<(payload: unknown) => void>>();
	const errorHandlers = new Set<(err: RpcError) => void>();
	const openHandlers = new Set<() => void>();
	// Frames requested via `send()` before the socket was open; flushed on open.
	const pendingSends: string[] = [];
	let ws: WebSocket | undefined;
	let reconnectDelayMs = 500;
	let reconnectTimer: ReturnType<typeof setTimeout> | undefined;

	// Server-assigned identity, persisted so it survives reloads and is
	// replayed (HTTP header + WS `?resume=`) to tie calls to the socket.
	const CLIENT_KEY = "draad.client";
	let clientId: string | null = readStoredClientId();

	function readStoredClientId(): string | null {
		try {
			return typeof sessionStorage !== "undefined" ? sessionStorage.getItem(CLIENT_KEY) : null;
		} catch { return null; }
	}
	function setClientId(id: unknown): void {
		if (typeof id !== "string" || !id || id === clientId) return;
		clientId = id;
		try { sessionStorage.setItem(CLIENT_KEY, id); } catch { /* ignore */ }
	}

	function fireError(err: RpcError): RpcError {
		// Notify every observer; a single throwing handler must not
		// take out the others, hence the per-handler try/catch.
		for (const h of errorHandlers) {
			try { h(err); } catch { /* swallow handler errors */ }
		}
		return err;
	}

	function flushPending(): void {
		if (!ws || ws.readyState !== WebSocket.OPEN) return;
		for (const frame of pendingSends.splice(0)) ws.send(frame);
	}

	function rawSend(frame: Record<string, unknown>): void {
		ensureWs();
		pendingSends.push(JSON.stringify(frame));
		flushPending();
	}

	function resumeUrl(): string {
		const base = opts.wsUrl!;
		if (!clientId) return base;
		return base + (base.includes("?") ? "&" : "?") + "resume=" + encodeURIComponent(clientId);
	}

	function openWs(): WebSocket {
		const sock = new WebSocket(resumeUrl());
		// Fire onOpen handlers exactly once per socket. On a fresh connect we
		// wait for the `$draad/welcome` frame first so handlers can read
		// `conn.id`; on a resume the id is already known, so fire on open.
		let firedOpen = false;
		const fireOpen = () => {
			if (firedOpen) return;
			firedOpen = true;
			for (const h of openHandlers) {
				try { h(); } catch { /* swallow handler errors */ }
			}
		};
		sock.addEventListener("open", () => {
			reconnectDelayMs = 500;
			// Restore every live subscription, then flush queued sends.
			for (const topic of subs.keys()) sock.send(JSON.stringify({ type: "subscribe", topic }));
			flushPending();
			if (clientId) fireOpen();
		});
		sock.addEventListener("message", (ev) => {
			try {
				const { topic, payload } = JSON.parse(String(ev.data));
				// draad's control frame: learn (or confirm) our id, then —
				// on a fresh connect — release the deferred onOpen handlers.
				if (topic === "$draad/welcome") {
					setClientId(payload?.clientId);
					fireOpen();
					return;
				}
				subs.get(topic)?.forEach((h) => h(payload));
			} catch {
				/* ignore malformed frames */
			}
		});
		sock.addEventListener("close", () => {
			ws = undefined;
			if (!shouldReconnect || subs.size === 0) return;
			const base = Math.min(reconnectDelayMs, maxDelayMs);
			const jitter = base * (0.8 + Math.random() * 0.4);
			reconnectDelayMs = Math.min(reconnectDelayMs * 2, maxDelayMs);
			reconnectTimer = setTimeout(() => {
				reconnectTimer = undefined;
				if (subs.size > 0 && !ws) ws = openWs();
			}, jitter);
		});
		return sock;
	}

	function ensureWs(): WebSocket {
		if (!opts.wsUrl) {
			throw new RpcError("NO_WS_URL", 0, null, "defaultRpc: wsUrl not configured; cannot listen()");
		}
		if (ws && ws.readyState !== WebSocket.CLOSED) return ws;
		ws = openWs();
		return ws;
	}

	return {
		get id(): string | null {
			return clientId;
		},
		async call<T>(command: string, args?: Record<string, unknown>, method: HttpVerb = "POST"): Promise<T> {
			const hasBody = method === "POST" || method === "PUT" || method === "PATCH";
			let url = `${baseUrl}/${command}`;
			const headers: Record<string, string> = { ...opts.headers };
			// Replay our identity so the server can tie this call to our socket.
			if (clientId) headers["x-draad-client"] = clientId;
			const init: RequestInit = { method, headers };
			if (hasBody) {
				(init.headers as Record<string, string>)["Content-Type"] = "application/json";
				init.body = JSON.stringify(args ?? {});
			} else if (args) {
				const params = new URLSearchParams();
				for (const [k, v] of Object.entries(args)) {
					if (v === undefined || v === null) continue;
					if (Array.isArray(v)) {
						for (const item of v) params.append(k, String(item));
					} else {
						params.append(k, String(v));
					}
				}
				const qs = params.toString();
				if (qs) url += `?${qs}`;
			}
			// Every failure path constructs an `RpcError`, fires the
			// global `onError` observers, then throws — so callers'
			// local try/catch and global handlers both see it.
			let res: Response;
			try {
				res = await fetch(url, init);
			} catch (e) {
				const msg = e instanceof Error ? e.message : String(e);
				throw fireError(new RpcError("NETWORK", 0, null, msg));
			}
			if (!res.ok) {
				// Best effort at giving callers the typed body their
				// `@throws` jsdoc promised: read once as text, try
				// JSON.parse, fall back to the raw string. Empty body
				// becomes null so `instanceof` checks stay clean.
				const raw = await res.text();
				let body: unknown = null;
				if (raw.length > 0) {
					try {
						body = JSON.parse(raw);
					} catch {
						body = raw;
					}
				}
				const message = typeof body === "string" ? body : res.statusText;
				throw fireError(new RpcError(`HTTP_${res.status}`, res.status, body as never, message));
			}
			try {
				return (await res.json()) as T;
			} catch (e) {
				const msg = e instanceof Error ? e.message : String(e);
				throw fireError(new RpcError("BAD_BODY", res.status, null, msg));
			}
		},
		listen<T>(topic: string, handler: (payload: T) => void): UnlistenFn {
			const sock = ensureWs();
			let set = subs.get(topic);
			const isFirst = !set;
			if (!set) {
				set = new Set();
				subs.set(topic, set);
			}
			const wrapped = handler as (p: unknown) => void;
			set.add(wrapped);
			// First listener for this topic asks the server to start sending
			// it. On a not-yet-open socket the `open` handler resubscribes
			// everything, so only send now if it's already connected.
			if (isFirst && sock.readyState === WebSocket.OPEN) {
				sock.send(JSON.stringify({ type: "subscribe", topic }));
			}
			return () => {
				set!.delete(wrapped);
				if (set!.size === 0) {
					subs.delete(topic);
					// Last listener gone: stop the server sending this topic.
					if (ws && ws.readyState === WebSocket.OPEN) {
						ws.send(JSON.stringify({ type: "unsubscribe", topic }));
					}
				}
				if (subs.size === 0 && reconnectTimer) {
					clearTimeout(reconnectTimer);
					reconnectTimer = undefined;
				}
			};
		},
		onOpen(handler: () => void): UnlistenFn {
			openHandlers.add(handler);
			// Already connected? Fire immediately so callers don't miss the
			// current session.
			if (ws && ws.readyState === WebSocket.OPEN) handler();
			return () => { openHandlers.delete(handler); };
		},
		send(frame: Record<string, unknown>): void {
			rawSend(frame);
		},
		onError(handler: (err: RpcError) => void): UnlistenFn {
			errorHandlers.add(handler);
			return () => { errorHandlers.delete(handler); };
		},
	};
}
